question_data = [
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "Which one of these was not a member of the Fiendish Five in the game Sly Cooper and the Thievius Raccoonus?",
     "correct_answer": "Dimitri Lousteau", "incorrect_answers": ["Mz. Ruby", "Muggshot", "Clockwerk"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Metallica collaborated with Rowan Atkinson&#039;s Mr Bean on a 1992 comic relief single.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "What is the name of the City in Saints Row The Third?", "correct_answer": "Steelport",
     "incorrect_answers": ["Stilwater", "Carcer", "Liberty"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "Which director directed the movie &quot;Pan&#039;s Labyrinth&quot;?",
     "correct_answer": "Guillermo Del Toro",
     "incorrect_answers": ["Alfonso Cuar&oacute;n", "Alejandro Gonz&aacute;lez I&ntilde;&aacute;rritu",
                           " Alejandro Jodorowsky"]},
    {"type": "multiple", "difficulty": "easy", "category": "Art",
                                                       "question": "Who painted the biblical fresco The Creation of Adam?",
                                                       "correct_answer": "Michelangelo",
                                                       "incorrect_answers": ["Leonardo da Vinci", "Caravaggio",
                                                                             "Rembrandt"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Board Games",
     "question": "When Magic: The Gathering was first solicited, which of the following was it originally titled?",
     "correct_answer": "Mana Clash", "incorrect_answers": ["Magic", "Magic Clash", "Mana Duels"]},
    {"type": "multiple", "difficulty": "easy", "category": "Mythology",
     "question": "Who in Greek mythology, who led the Argonauts in search of the Golden Fleece?",
     "correct_answer": "Jason", "incorrect_answers": ["Castor", "Daedalus", "Odysseus"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "The Sonoran Desert is located in eastern Africa.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
                                      "question": "What fast food chain has the most locations globally? ",
                                      "correct_answer": "Subway",
                                      "incorrect_answers": ["Starbucks", "McDonalds", "KFC"]}]
